{{- if and .Values.priorityClass.enabled (not .Values.priorityClass.useExisting) -}}
apiVersion: scheduling.k8s.io/v1
description: The vitess-operator control plane.
globalDefault: false
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.vitessOperatorControlPlane.name }}
value: {{ .Values.priorityClass.vitessOperatorControlPlane.value }}
{{- end -}}
